spring:
  application:
    name: api-agenda

  datasource:
    url: jdbc:mysql://localhost:3307/bd-agenda?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
    username: coti
    password: Coti2026
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
      host: localhost
      port: 5672
      username: coti
      password: coti
      virtual-host: /
      queue-name: notificacoes


server:
  port: 8083

cors:
  enabled: http://localhost:4200

jwt:
  secret: 537fb3d6-1192-425e-8142-1e8f4201944e
  expiration: 3600000